### ISSUE TITLE
Extension should be "csv" instead of "cvs"?

### ISSUE THREAD

**Issue by axkr** [hallvard/etablesaw#2]
The `extensions` should be "csv" instead of "cvs"?

- https://github.com/hallvard/etablesaw/blob/2fc40dd35401bbe4f249f2b5f3b415dd1d52d4e8/etablesaw/etablesaw.ui/plugin.xml#L12

Otherwise the tablesaw editor doesn't appear in the context menu (right mouse click on file) for `*.csv` files
![grafik](https://user-images.githubusercontent.com/3109793/74586644-c89e1900-4fe9-11ea-9b69-79823bfb3599.png)

**Comment by hallvard** [comment]
Of course, I tend to make the same mistake when naming classes, I use cvs instead csv.
